"""
PDF report generator for DUEL battle results.
Produces a professional multi-page PDF using reportlab only.
"""

import html
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Flowable, KeepTogether,
)

from engine.scoring import BattleScorer, _BattleAnalyst, OUTPUT_DIR

logger = logging.getLogger(__name__)

_TECHNIQUES_DIR = Path(__file__).parent.parent / "techniques"

# ---------------------------------------------------------------------------
# Print-safe colour palette (dark navy headers, red/blue accents, white body)
# ---------------------------------------------------------------------------

_C = {
    "navy":   HexColor("#0d1117"),
    "dark":   HexColor("#111827"),
    "border": HexColor("#334155"),
    "red":    HexColor("#c0392b"),
    "blue":   HexColor("#1a5cbf"),
    "green":  HexColor("#007a44"),
    "yellow": HexColor("#9a6f00"),
    "text":   HexColor("#1a202c"),
    "muted":  HexColor("#64748b"),
    "alt":    HexColor("#f7f9fc"),
    "code":   HexColor("#f1f5f9"),
    "bar_bg": HexColor("#e2e8f0"),
}

_PAGE_W, _PAGE_H = A4
_MARGIN     = 20 * mm
_CONTENT_W  = _PAGE_W - 2 * _MARGIN

_FOOTER = (
    "Generated by DUEL — Dual Unsupervised Evasion Loop  ·  "
    "github.com/0xDanielSec/duel-framework"
)


# ---------------------------------------------------------------------------
# Detection-rate bar — drawn inline inside table cells
# ---------------------------------------------------------------------------

class _RateBar(Flowable):
    def __init__(self, rate: float, width: float = 72, height: float = 9):
        super().__init__()
        self.rate  = max(0.0, min(1.0, rate))
        self.width = width
        self.height = height

    def wrap(self, *_):
        return self.width, self.height

    def draw(self):
        c     = self.canv
        fill  = self.width * self.rate
        color = _C["blue"] if self.rate >= 0.5 else _C["red"]
        c.setFillColor(_C["bar_bg"])
        c.rect(0, 0, self.width, self.height, fill=1, stroke=0)
        if fill > 0:
            c.setFillColor(color)
            c.rect(0, 0, fill, self.height, fill=1, stroke=0)
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(white if self.rate >= 0.35 else _C["text"])
        c.drawCentredString(self.width / 2, 1.5, f"{self.rate:.0%}")


# ---------------------------------------------------------------------------
# Style registry
# ---------------------------------------------------------------------------

def _styles() -> dict[str, ParagraphStyle]:
    def s(name, **kw):
        return ParagraphStyle(name, **kw)
    return {
        "cover_title": s("cover_title", fontName="Helvetica-Bold", fontSize=34,
                          textColor=white, alignment=TA_CENTER, leading=40),
        "cover_sub":   s("cover_sub",   fontName="Helvetica", fontSize=11,
                          textColor=HexColor("#8a9ab5"), alignment=TA_CENTER),
        "pg_title":    s("pg_title",    fontName="Helvetica-Bold", fontSize=15,
                          textColor=white, alignment=TA_LEFT),
        "pg_sub":      s("pg_sub",      fontName="Helvetica", fontSize=9,
                          textColor=HexColor("#94a3b8"), alignment=TA_LEFT),
        "section":     s("section",     fontName="Helvetica-Bold", fontSize=11,
                          textColor=_C["navy"], spaceBefore=5*mm, spaceAfter=2*mm),
        "body":        s("body",        fontName="Helvetica", fontSize=9,
                          textColor=_C["text"], leading=14, spaceAfter=2*mm),
        "label":       s("label",       fontName="Helvetica-Bold", fontSize=8,
                          textColor=_C["muted"], spaceAfter=1*mm),
        "cell":        s("cell",        fontName="Helvetica", fontSize=8,
                          textColor=_C["text"], leading=11),
        "cell_b":      s("cell_b",      fontName="Helvetica-Bold", fontSize=8,
                          textColor=_C["text"], leading=11),
        "code":        s("code",        fontName="Courier", fontSize=8,
                          textColor=_C["text"], leading=12),
        "caption":     s("caption",     fontName="Helvetica-Oblique", fontSize=8,
                          textColor=_C["muted"]),
    }


# ---------------------------------------------------------------------------
# Shared drawing helpers
# ---------------------------------------------------------------------------

def _section_header(title: str, subtitle: str = "") -> list:
    """Dark navy header block — used at the top of every section page."""
    ST = _styles()
    rows = [[Paragraph(title, ST["pg_title"])]]
    if subtitle:
        rows.append([Paragraph(subtitle, ST["pg_sub"])])
    t = Table(rows, colWidths=[_CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), _C["navy"]),
        ("TOPPADDING",    (0, 0), (-1, 0),  5 * mm),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 4 * mm),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4 * mm),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4 * mm),
    ]))
    return [t, Spacer(1, 5 * mm)]


def _col_table(data: list[list], col_widths: list[float],
               header_bg=None, alt_rows=True, small: bool = False) -> Table:
    """Styled table with optional coloured header and alternating row shading."""
    header_bg = header_bg or _C["dark"]
    fs = 7 if small else 8
    # Wrap plain strings in data rows as Paragraphs so they word-wrap within cells
    wrapped = []
    for r_idx, row in enumerate(data):
        if r_idx == 0:
            wrapped.append(row)
        else:
            wrapped.append([
                _cp(cell, small=small) if isinstance(cell, str) else cell
                for cell in row
            ])
    t = Table(wrapped, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND",    (0, 0), (-1, 0),  header_bg),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  white),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), fs),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR",     (0, 1), (-1, -1), _C["text"]),
        ("ALIGN",         (0, 0), (-1, 0),  "CENTER"),
        ("ALIGN",         (0, 1), (-1, -1), "LEFT"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
        ("GRID",          (0, 0), (-1, -1), 0.4, _C["border"]),
    ]
    if alt_rows:
        for i in range(1, len(wrapped)):
            if i % 2 == 0:
                style.append(("BACKGROUND", (0, i), (-1, i), _C["alt"]))
    t.setStyle(TableStyle(style))
    return t


def _code_block(text: str) -> Table:
    """KQL/text in a light-grey monospace box with a coloured left border."""
    safe = html.escape(text.strip()).replace('\n', '<br/>')
    para = Paragraph(safe, ParagraphStyle(
        "code_wrap", fontName="Courier", fontSize=7,
        textColor=_C["text"], leading=10,
        leftIndent=4, rightIndent=4, wordWrap='LTR',
    ))
    t = Table([[para]], colWidths=[_CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), _C["code"]),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 3 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3 * mm),
        ("LINEAFTER",     (0, 0), (-1, -1), 0, white),
        ("LINEBEFORE",    (0, 0), (-1, -1), 3, _C["blue"]),
        ("BOX",           (0, 0), (-1, -1), 0.4, _C["border"]),
    ]))
    return t


def _sev(rate: float) -> tuple[str, HexColor]:
    if rate >= 0.7:
        return "HIGH",   _C["red"]
    if rate >= 0.4:
        return "MEDIUM", _C["yellow"]
    return "LOW", _C["green"]


def _page_footer(canvas, doc):
    canvas.saveState()
    y = _MARGIN - 8 * mm
    canvas.setStrokeColor(_C["border"])
    canvas.setLineWidth(0.5)
    canvas.line(_MARGIN, y + 3.5 * mm, _PAGE_W - _MARGIN, y + 3.5 * mm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_C["muted"])
    canvas.drawString(_MARGIN, y, _FOOTER)
    canvas.drawRightString(_PAGE_W - _MARGIN, y, f"Page {doc.page}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# ReportGenerator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """
    Builds a professional PDF report from a completed BattleScorer instance.

    Usage:
        rg   = ReportGenerator(scorer)
        path = rg.generate()          # → Path to output/duel_report_*.pdf
    """

    def __init__(self, scorer: BattleScorer):
        self.scorer    = scorer
        self.tid       = scorer.technique_id
        self.tech_name = self._load_tech_name()
        self.analyst   = _BattleAnalyst(scorer.rounds, self.tid)
        self.ST        = _styles()
        self.winner    = self._winner()
        self.total_logs = sum(r["attack_log_count"] for r in scorer.rounds)
        self.total_det  = sum(r["detected_count"]   for r in scorer.rounds)
        self.det_rate   = self.total_det / self.total_logs if self.total_logs else 0.0
        self.eva_rate   = 1.0 - self.det_rate

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def generate(self) -> Path:
        """Build the PDF and return its path."""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        path = OUTPUT_DIR / f"duel_report_{self.tid}_{date_str}.pdf"

        doc = SimpleDocTemplate(
            str(path),
            pagesize=A4,
            leftMargin=_MARGIN, rightMargin=_MARGIN,
            topMargin=_MARGIN,  bottomMargin=_MARGIN + 10 * mm,
            title=f"DUEL Report — {self.tid}",
            author="DUEL Framework",
            subject=f"Adversarial detection analysis — {self.tid}",
        )
        story = (
            self._page_cover()
            + [PageBreak()]
            + self._page_statistics()
            + [PageBreak()]
            + self._page_mutations()
            + [PageBreak()]
            + self._page_kql_rules()
            + [PageBreak()]
            + self._page_gaps()
            + [PageBreak()]
            + self._page_recommendations()
        )
        doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
        logger.info("PDF report saved to %s", path)
        return path

    # ------------------------------------------------------------------
    # Page 1 — Cover
    # ------------------------------------------------------------------

    def _page_cover(self) -> list:
        ST   = self.ST
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        w_color = _C["red"] if self.winner == "Attacker" \
                  else _C["blue"] if self.winner == "Defender" \
                  else _C["yellow"]

        # ── Hero header ────────────────────────────────────────────────
        hero_data = [
            [Paragraph("⚔  D U E L", ST["cover_title"])],
            [Paragraph("Dual Unsupervised Evasion Loop", ST["cover_sub"])],
        ]
        hero = Table(hero_data, colWidths=[_CONTENT_W])
        hero.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), _C["navy"]),
            ("TOPPADDING",    (0, 0), (-1, 0),  14 * mm),
            ("BOTTOMPADDING", (0, -1), (-1, -1), 10 * mm),
        ]))

        # ── Meta info ──────────────────────────────────────────────────
        meta_rows = [
            [_p("TECHNIQUE",      ST["label"]), _p(f"{self.tid} — {self.tech_name}", ST["cell"])],
            [_p("DATE",           ST["label"]), _p(date,                             ST["cell"])],
            [_p("ROUNDS PLAYED",  ST["label"]), _p(f"{len(self.scorer.rounds)} of {self.scorer.total_rounds}", ST["cell"])],
            [_p("WINNER",         ST["label"]), Paragraph(f'<font color="#{_hex(w_color)}"><b>{self.winner.upper()}</b></font>', ST["cell"])],
        ]
        meta = Table(meta_rows, colWidths=[38 * mm, _CONTENT_W - 38 * mm])
        meta.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 2),
            ("LINEBELOW",     (0, 0), (-1, -2), 0.3, _C["border"]),
        ]))

        # ── Score summary ──────────────────────────────────────────────
        sc_hdr = [_p("ATTACKER", ST["label"]), _p("DEFENDER", ST["label"]),
                  _p("DETECTION RATE", ST["label"]), _p("EVASION RATE", ST["label"])]
        sc_vals = [
            Paragraph(f'<font color="#{_hex(_C["red"])}" size="22"><b>{self.scorer.attacker_score}</b></font>', ST["cell"]),
            Paragraph(f'<font color="#{_hex(_C["blue"])}" size="22"><b>{self.scorer.defender_score}</b></font>', ST["cell"]),
            _p(f"{self.det_rate:.0%}", ParagraphStyle("big", fontName="Helvetica-Bold", fontSize=22, textColor=_C["text"])),
            _p(f"{self.eva_rate:.0%}", ParagraphStyle("big2", fontName="Helvetica-Bold", fontSize=22, textColor=_C["text"])),
        ]
        sc = Table([sc_hdr, sc_vals], colWidths=[_CONTENT_W * 0.25] * 4)
        sc.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  _C["dark"]),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  _C["muted"]),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, 0),  8),
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("BOX",           (0, 0), (-1, -1), 0.5, _C["border"]),
            ("INNERGRID",     (0, 0), (-1, -1), 0.3, _C["border"]),
        ]))

        # ── Executive summary ──────────────────────────────────────────
        exec_body = self._exec_summary_text()

        return [
            hero, Spacer(1, 6 * mm),
            meta, Spacer(1, 5 * mm),
            _p("BATTLE OUTCOME", ST["label"]),
            sc, Spacer(1, 6 * mm),
            _p("EXECUTIVE SUMMARY", ST["label"]),
            _p(exec_body, ST["body"]),
        ]

    # ------------------------------------------------------------------
    # Page 2 — Battle Statistics
    # ------------------------------------------------------------------

    def _page_statistics(self) -> list:
        ST = self.ST
        story = _section_header(
            "BATTLE STATISTICS",
            f"{self.tid} — {self.tech_name}  ·  {len(self.scorer.rounds)} rounds",
        )
        story.append(_p("Round-by-round detection performance", ST["label"]))

        if not self.scorer.rounds:
            story.append(_p("No rounds recorded.", ST["body"]))
            return story

        bar_w = 65
        hdr = ["RND", "LOGS", "DETECTED", "EVADED", "RATE", "", "RESULT"]
        _fixed = (12 + 18 + 16 + 24) * mm          # narrow fixed cols
        _split = (_CONTENT_W - _fixed - bar_w) / 2  # share remaining between DET/EVADED
        col_w = [12*mm, 18*mm, _split, _split, 16*mm, bar_w, 24*mm]
        rows = [hdr]
        for r in self.scorer.rounds:
            result   = "DETECTED" if r["detected_count"] >= r["evaded_count"] else "EVADED"
            r_color  = _C["blue"] if result == "DETECTED" else _C["red"]
            rows.append([
                str(r["round"]),
                str(r["attack_log_count"]),
                str(r["detected_count"]),
                str(r["evaded_count"]),
                f"{r['detection_rate']:.0%}",
                _RateBar(r["detection_rate"], width=bar_w),
                Paragraph(f'<font color="#{_hex(r_color)}"><b>{result}</b></font>',
                          ParagraphStyle("res", fontName="Helvetica-Bold", fontSize=8,
                                         alignment=TA_CENTER)),
            ])
        t = Table(rows, colWidths=col_w, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  _C["dark"]),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  white),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("ALIGN",         (0, 0), (-1, 0),  "CENTER"),
            ("ALIGN",         (0, 1), (-1, -1), "CENTER"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 4),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
            ("GRID",          (0, 0), (-1, -1), 0.4, _C["border"]),
        ] + [("BACKGROUND", (0, i), (-1, i), _C["alt"]) for i in range(2, len(rows), 2)]))
        story.append(t)

        # Cumulative score progression
        story.append(Spacer(1, 5 * mm))
        story.append(_p("CUMULATIVE SCORE PROGRESSION", ST["label"]))
        prog_hdr = ["ROUND", "ATT CUM.", "DEF CUM.", "ROUND WINNER"]
        prog_rows = [prog_hdr]
        for r in self.scorer.rounds:
            rw = "Attacker" if r["evaded_count"] > r["detected_count"] else "Defender"
            prog_rows.append([
                str(r["round"]),
                str(r["attacker_cumulative_score"]),
                str(r["defender_cumulative_score"]),
                rw,
            ])
        prog_cw = [20*mm, 35*mm, 35*mm, _CONTENT_W - 90*mm]
        story.append(_col_table(prog_rows, prog_cw))
        return story

    # ------------------------------------------------------------------
    # Page 3 — Attacker Mutation Analysis
    # ------------------------------------------------------------------

    def _page_mutations(self) -> list:
        ST = self.ST
        story = _section_header(
            "ATTACKER MUTATION ANALYSIS",
            "How the Attacker adapted across rounds to evade detection",
        )

        if len(self.scorer.rounds) < 2:
            story.append(_p("At least 2 rounds are required for mutation analysis.", ST["body"]))
            return story

        stable, rotating = self.analyst._classify_fields()

        # Stable signatures
        story.append(Paragraph("Stable Attack Signatures", ST["section"]))
        story.append(_p(
            "Fields that held the same value in every round — "
            "the highest-confidence IOCs the Attacker did not rotate.", ST["body"]))

        if stable:
            hdr = ["FIELD", "STABLE VALUE(S)", "ROUNDS PRESENT"]
            rows = [hdr]
            for field, values in sorted(stable.items()):
                vals = ", ".join(sorted(str(v) for v in values)[:5])
                if len(values) > 5:
                    vals += f"  +{len(values)-5} more"
                rows.append([field, vals, f"all {len(self.scorer.rounds)}"])
            story.append(_col_table(rows, [45*mm, _CONTENT_W - 90*mm, 45*mm], small=True))
        else:
            story.append(_p("The Attacker rotated all tracked fields — no stable signatures.", ST["body"]))

        # Mutation vectors
        story.append(Paragraph("Mutation Vectors", ST["section"]))
        story.append(_p(
            "Fields that changed between rounds. [reactive] marks fields the Defender "
            "targeted in the previous round's KQL rule — indicating the Attacker "
            "read and evaded the rule.", ST["body"]))
        story.append(Spacer(1, 2 * mm))

        ev = self.analyst._evaded_values
        kf = self.analyst._kql_fields
        any_delta = False
        for i in range(1, len(self.scorer.rounds)):
            prev_r = self.scorer.rounds[i - 1]["round"]
            curr_r = self.scorer.rounds[i]["round"]
            prev_kql_fields = kf.get(prev_r, set())
            deltas = []
            for field in rotating:
                prev_v = ev.get(prev_r, {}).get(field, set())
                curr_v = ev.get(curr_r, {}).get(field, set())
                added, removed = curr_v - prev_v, prev_v - curr_v
                if added or removed:
                    reactive = " [reactive]" if field in prev_kql_fields else ""
                    parts = []
                    if removed:
                        parts.append("dropped " + ", ".join(str(v) for v in sorted(removed)[:3]))
                    if added:
                        parts.append("added " + ", ".join(str(v) for v in sorted(added)[:3]))
                    deltas.append([field + reactive, "; ".join(parts)])
            if deltas:
                any_delta = True
                block_title = _p(f"Round {prev_r} → Round {curr_r}", ST["cell_b"])
                hdr = ["FIELD", "CHANGE"]
                cw  = [50*mm, _CONTENT_W - 50*mm]
                t   = _col_table([hdr] + deltas, cw, small=True)
                story.append(KeepTogether([block_title, Spacer(1, 1*mm), t, Spacer(1, 3*mm)]))

        if not any_delta:
            story.append(_p("No field-level mutations detected between rounds.", ST["body"]))
        return story

    # ------------------------------------------------------------------
    # Page 4 — Surviving KQL Rules
    # ------------------------------------------------------------------

    def _page_kql_rules(self) -> list:
        ST = self.ST
        story = _section_header(
            "KQL RULES THAT SURVIVED",
            "Detection rules that caught at least one attack log",
        )

        if not self.scorer.surviving_kql:
            story.append(_p("No rules successfully detected any attack logs.", ST["body"]))
            return story

        story.append(_p(
            f"{len(self.scorer.surviving_kql)} rule(s) detected attack traffic. "
            "Severity is derived from the per-round detection rate.", ST["body"]))

        for i, rule in enumerate(self.scorer.surviving_kql, 1):
            sev_label, sev_color = _sev(rule["detection_rate"])
            sev_hex = _hex(sev_color)
            title_text = (
                f'Rule {i} — Round {rule["round"]}  '
                f'<font color="#{sev_hex}"><b>[{sev_label}]</b></font>  '
                f'· Detection rate: {rule["detection_rate"]:.0%}'
            )
            block = [
                Paragraph(title_text, ParagraphStyle(
                    "rule_title", fontName="Helvetica-Bold", fontSize=9,
                    textColor=_C["text"], spaceBefore=4*mm, spaceAfter=1*mm)),
                _code_block(rule["kql"]),
                Spacer(1, 2 * mm),
            ]
            story.append(KeepTogether(block))
        return story

    # ------------------------------------------------------------------
    # Page 5 — Detection Gaps
    # ------------------------------------------------------------------

    def _page_gaps(self) -> list:
        ST = self.ST
        story = _section_header(
            "DETECTION GAPS",
            "Fields never covered by any rule — persistent missed opportunities",
        )
        gaps = self.analyst._gap_fields()

        if not gaps:
            story.append(_p(
                "No persistent unaddressed signals found. "
                "The Defender's rules touched every consistently-present field. "
                "Evasion was caused by threshold or value mismatches, not blind spots.",
                ST["body"]))
            return story

        story.append(_p(
            "The following fields appeared in a high percentage of evaded logs "
            "across every round but were never referenced by any Defender rule. "
            "Each is a missed detection opportunity.", ST["body"]))

        hdr  = ["FIELD", "STABLE VALUE(S)", "EVADED LOG PRESENCE", "ROUNDS NEVER TARGETED"]
        rows = [hdr]
        for field, (values, pct) in gaps.items():
            vals = ", ".join(sorted(str(v) for v in values)[:3])
            if len(values) > 3:
                vals += f"  +{len(values)-3}"
            rows.append([field, vals, f"{pct:.0%}", f"all {len(self.scorer.rounds)}"])
        cw = [38*mm, _CONTENT_W - 101*mm, 28*mm, 35*mm]
        story.append(_col_table(rows, cw, small=True))

        # Recommended KQL for each gap field that has a remediation
        rem = _BattleAnalyst.FIELD_REMEDIATION
        covered = [f for f in gaps if f in rem]
        if covered:
            story.append(Spacer(1, 4 * mm))
            story.append(Paragraph("Recommended KQL Snippets", ST["section"]))
            story.append(_p(
                "These rules would directly address the gaps identified above.", ST["body"]))
            for field in covered:
                conf, title, kql_text = rem[field]
                story.append(KeepTogether([
                    _p(f"{field} — {title}", ST["cell_b"]),
                    Spacer(1, 1 * mm),
                    _code_block(kql_text),
                    Spacer(1, 3 * mm),
                ]))
        return story

    # ------------------------------------------------------------------
    # Page 6 — Sentinel Deployment Recommendations
    # ------------------------------------------------------------------

    def _page_recommendations(self) -> list:
        ST = self.ST
        story = _section_header(
            "SENTINEL DEPLOYMENT RECOMMENDATIONS",
            "Ordered by priority — High → Medium → Low",
        )
        story.append(_p(
            "Derived from fields that carried a stable, high-confidence attack signal "
            "across every round but were never addressed by any detection rule.",
            ST["body"]))

        gaps  = self.analyst._gap_fields()
        rem   = _BattleAnalyst.FIELD_REMEDIATION
        evaded_fields = set(self.analyst._all_evaded[0].keys()) if self.analyst._all_evaded else set()

        added: set[str] = set()
        buckets: dict[str, list] = {"High": [], "Medium": [], "Low": []}

        for field in gaps:
            if field in rem and field not in added:
                buckets[rem[field][0]].append((field, rem[field][1], rem[field][2], "gap"))
                added.add(field)
        for field in ("ConditionalAccessStatus", "AuthenticationRequirement"):
            if field not in added and field in rem:
                buckets[rem[field][0]].append((field, rem[field][1], rem[field][2], "structural"))
                added.add(field)
        for field, (conf, title, kql_text) in rem.items():
            if field not in added and field in evaded_fields:
                buckets[conf].append((field, title, kql_text, "supplemental"))
                added.add(field)

        if not any(buckets.values()):
            story.append(_p("No specific recommendations could be derived.", ST["body"]))
            return story

        origin_labels = {
            "gap":          "directly addresses a detected gap",
            "structural":   "structural control — baseline for any deployment",
            "supplemental": "supplemental — covers additional evasion surface",
        }

        rule_num = 0
        for conf in ("High", "Medium", "Low"):
            conf_color = _sev({"High": 0.9, "Medium": 0.55, "Low": 0.2}[conf])[1]
            for field, title, kql_text, origin in buckets[conf]:
                rule_num += 1
                pct = self.analyst._field_presence_pct(field, self.analyst._all_evaded)
                badge_hex = _hex(conf_color)
                heading = (
                    f'<font color="#{badge_hex}"><b>[{conf.upper()} PRIORITY]</b></font>'
                    f'  Rule {rule_num}: {title}'
                )
                rationale = (
                    f"`{field}` appeared in {pct:.0%} of evaded logs — "
                    f"this rule {origin_labels[origin]}."
                )
                story.append(KeepTogether([
                    Paragraph(heading, ParagraphStyle(
                        "rec_h", fontName="Helvetica-Bold", fontSize=9,
                        textColor=_C["text"], spaceBefore=5*mm, spaceAfter=1*mm)),
                    _p(f"Rationale: {rationale}", ST["body"]),
                    _code_block(kql_text),
                    Spacer(1, 2 * mm),
                ]))

        story += [
            Spacer(1, 5 * mm),
            Paragraph("Operational Notes", ST["section"]),
            _p(
                "• Tune count thresholds against your environment's baseline before enabling alerts.\n"
                "• Enrich IPAddress through ThreatIntelligenceIndicator for Tor/hosting-provider scoring.\n"
                "• Combine ConditionalAccessStatus == \"notApplied\" with AuthenticationRequirement == "
                "\"singleFactorAuthentication\" — both were stable signals throughout this battle.\n"
                "• Enable Entra ID Identity Protection to enforce risk-based CA policies that block "
                "suspicious logins at the authentication layer.",
                ST["body"]),
        ]
        return story

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _winner(self) -> str:
        if self.scorer.attacker_score > self.scorer.defender_score:
            return "Attacker"
        if self.scorer.defender_score > self.scorer.attacker_score:
            return "Defender"
        return "Draw"

    def _load_tech_name(self) -> str:
        try:
            with open(_TECHNIQUES_DIR / f"{self.tid}.json", encoding="utf-8") as f:
                return json.load(f)["name"]
        except Exception:
            return self.tid

    def _exec_summary_text(self) -> str:
        total_evaded = self.total_logs - self.total_det
        gaps = self.analyst._gap_fields()
        top_gap = next(iter(gaps), None)
        gap_line = ""
        if top_gap:
            _, pct = gaps[top_gap]
            gap_line = (
                f" The most critical unaddressed signal was '{top_gap}', "
                f"present in {pct:.0%} of all evaded logs and never referenced by any "
                f"Defender rule."
            )
        return (
            f"The Attacker evaded detection on {total_evaded} of {self.total_logs} logs "
            f"({self.eva_rate:.0%}) across {len(self.scorer.rounds)} rounds against technique "
            f"{self.tid} ({self.tech_name}). "
            f"The Defender's KQL rules detected {self.total_det} logs ({self.det_rate:.0%} detection rate)."
            f"{gap_line} "
            "The sections that follow detail how the Attacker mutated, why each Defender rule failed, "
            "which detection gaps were left open, and what rules a real Sentinel deployment should add."
        )


# ---------------------------------------------------------------------------
# Convenience shorthands
# ---------------------------------------------------------------------------

def _p(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(text, style)


def _cp(text: str, small: bool = False) -> Paragraph:
    """Paragraph for table data cells — wraps within the cell boundary."""
    fs = 7 if small else 8
    return Paragraph(str(text), ParagraphStyle(
        "cp", fontName="Helvetica", fontSize=fs,
        textColor=_C["text"], leading=fs + 3,
    ))


def _hex(color) -> str:
    """Bare 6-char hex from a ReportLab color; handles both '#rrggbb' and '0xrrggbb' prefixes."""
    return color.hexval()[-6:]
