"""
DUEL — Sentinel Export Engine
Converts surviving KQL rules from battle logs into production-ready
Microsoft Sentinel Analytics Rules in ARM template format.
"""

import json
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

OUTPUT_DIR     = Path(__file__).parent.parent / "output"
TECHNIQUES_DIR = Path(__file__).parent.parent / "techniques"

# MITRE tactic display name → Sentinel ARM tactic enum
TACTIC_MAP: dict[str, str] = {
    "Initial Access":       "InitialAccess",
    "Execution":            "Execution",
    "Persistence":          "Persistence",
    "Privilege Escalation": "PrivilegeEscalation",
    "Defense Evasion":      "DefenseEvasion",
    "Credential Access":    "CredentialAccess",
    "Discovery":            "Discovery",
    "Lateral Movement":     "LateralMovement",
    "Collection":           "Collection",
    "Command and Control":  "CommandAndControl",
    "Exfiltration":         "Exfiltration",
    "Impact":               "Impact",
}


def _severity_from_evasion(evasion_rate: float) -> str:
    if evasion_rate > 0.8:
        return "High"
    if evasion_rate >= 0.5:
        return "Medium"
    return "Low"


def _map_tactics(tactic_str: str) -> list[str]:
    """Map comma-separated MITRE tactic names to Sentinel ARM enum values."""
    result: list[str] = []
    for t in tactic_str.split(","):
        mapped = TACTIC_MAP.get(t.strip())
        if mapped and mapped not in result:
            result.append(mapped)
    return result or ["DefenseEvasion"]


class SentinelExporter:
    def __init__(self):
        self._tech_cache: dict[str, dict] = {}

    # ------------------------------------------------------------------
    # Technique loader
    # ------------------------------------------------------------------

    def _load_technique(self, technique_id: str) -> dict:
        if technique_id not in self._tech_cache:
            path = TECHNIQUES_DIR / f"{technique_id}.json"
            if path.exists():
                with open(path, encoding="utf-8") as f:
                    self._tech_cache[technique_id] = json.load(f)
            else:
                self._tech_cache[technique_id] = {
                    "technique_id": technique_id,
                    "name": technique_id,
                    "tactic": "Defense Evasion",
                }
        return self._tech_cache[technique_id]

    # ------------------------------------------------------------------
    # Rule loading
    # ------------------------------------------------------------------

    def load_rules(self) -> list[dict]:
        """
        Scan output/full_battle_log_*.json and return all rounds where
        detection_rate > 0 (rule caught at least one log).

        Each returned rule dict has:
          id, technique_id, technique_name, tactic, tactics, round,
          detection_rate, evasion_rate, severity, kql,
          display_name, description
        """
        rules: list[dict] = []

        for log_path in sorted(OUTPUT_DIR.glob("full_battle_log_*.json")):
            try:
                with open(log_path, encoding="utf-8") as f:
                    battle = json.load(f)
            except Exception:
                continue

            technique_id = battle.get("technique_id", "")
            if not technique_id or not isinstance(battle.get("rounds"), list):
                continue

            tech       = self._load_technique(technique_id)
            tactic_str = tech.get("tactic", "Defense Evasion")

            for round_rec in battle["rounds"]:
                det_rate = float(round_rec.get("detection_rate", 0.0))
                if det_rate <= 0:
                    continue

                round_num = round_rec.get("round", 0)
                eva_rate  = float(round_rec.get("evasion_rate", 0.0))
                kql       = round_rec.get("kql_rule", "").strip()
                if not kql:
                    continue

                severity     = _severity_from_evasion(eva_rate)
                tactics      = _map_tactics(tactic_str)
                tactic_short = tactic_str.split(",")[0].strip()
                display_name = (
                    f"DUEL - {technique_id} - {tactic_short} - Round {round_num}"
                )
                description = (
                    f"Auto-generated by DUEL adversarial testing. "
                    f"Technique: {technique_id} ({tech.get('name', technique_id)}). "
                    f"Tactic: {tactic_str}. "
                    f"Detection rate in simulation: {det_rate:.0%}. "
                    f"Evasion rate: {eva_rate:.0%}. "
                    f"Rule survived round {round_num} of adversarial testing "
                    f"against a live LLM attacker. "
                    f"Severity mapped from evasion rate: {severity}."
                )

                rules.append({
                    "id":             f"{technique_id}_round{round_num}",
                    "technique_id":   technique_id,
                    "technique_name": tech.get("name", technique_id),
                    "tactic":         tactic_str,
                    "tactics":        tactics,
                    "round":          round_num,
                    "detection_rate": round(det_rate, 4),
                    "evasion_rate":   round(eva_rate, 4),
                    "severity":       severity,
                    "kql":            kql,
                    "display_name":   display_name,
                    "description":    description,
                })

        # Deduplicate by (technique_id, round) — latest battle wins
        seen: dict[str, dict] = {}
        for rule in rules:
            key = rule["id"]
            if key not in seen or rule["detection_rate"] > seen[key]["detection_rate"]:
                seen[key] = rule

        return sorted(seen.values(), key=lambda r: (r["technique_id"], r["round"]))

    # ------------------------------------------------------------------
    # ARM template builder
    # ------------------------------------------------------------------

    def to_arm_template(self, rules: list[dict]) -> dict:
        """Bundle rule dicts into a single ARM deployment template."""
        resources = []
        for rule in rules:
            rule_guid = str(uuid.uuid5(uuid.NAMESPACE_DNS, rule["id"]))
            resources.append({
                "type": "Microsoft.OperationalInsights/workspaces/providers/alertRules",
                "name": (
                    f"[concat(parameters('workspaceName'), "
                    f"'/Microsoft.SecurityInsights/{rule_guid}')]"
                ),
                "apiVersion": "2022-11-01-preview",
                "kind": "Scheduled",
                "properties": {
                    "displayName":      rule["display_name"],
                    "description":      rule["description"],
                    "severity":         rule["severity"],
                    "enabled":          True,
                    "query":            rule["kql"],
                    "queryFrequency":   "PT1H",
                    "queryPeriod":      "PT1H",
                    "triggerOperator":  "GreaterThan",
                    "triggerThreshold": 0,
                    "suppressionDuration": "PT5H",
                    "suppressionEnabled":  False,
                    "tactics":    rule["tactics"],
                    "techniques": [rule["technique_id"]],
                    "alertRuleTemplateName": None,
                    "incidentConfiguration": {
                        "createIncident": True,
                        "groupingConfiguration": {
                            "enabled":              False,
                            "reopenClosedIncident": False,
                            "lookbackDuration":     "PT5H",
                            "matchingMethod":       "AllEntities",
                            "groupByEntities":      [],
                            "groupByAlertDetails":  [],
                            "groupByCustomDetails": [],
                        },
                    },
                    "eventGroupingSettings": {"aggregationKind": "SingleAlert"},
                    "entityMappings":    None,
                    "alertDetailsOverride": None,
                    "customDetails":     None,
                },
            })

        return {
            "$schema": (
                "https://schema.management.azure.com/schemas/"
                "2019-04-01/deploymentTemplate.json#"
            ),
            "contentVersion": "1.0.0.0",
            "parameters": {
                "workspaceName": {
                    "type": "string",
                    "metadata": {
                        "description": (
                            "Name of the Microsoft Sentinel "
                            "(Log Analytics) workspace."
                        )
                    },
                }
            },
            "resources": resources,
            "_metadata": {
                "generatedBy":  "DUEL — Dual Unsupervised Evasion Loop",
                "generatedAt":  datetime.now(timezone.utc).isoformat(),
                "totalRules":   len(rules),
            },
        }

    # ------------------------------------------------------------------
    # High-level export
    # ------------------------------------------------------------------

    def export(
        self,
        severity_filter: list[str] | None = None,
        id_filter: list[str] | None = None,
    ) -> tuple[dict, Path, Path]:
        """
        Load rules, apply optional filters, write ARM JSON + markdown.
        Returns (arm_dict, json_path, md_path).
        """
        OUTPUT_DIR.mkdir(exist_ok=True)
        rules = self.load_rules()

        if id_filter:
            id_set = set(id_filter)
            rules = [r for r in rules if r["id"] in id_set]
        elif severity_filter:
            sev_set = set(severity_filter)
            rules = [r for r in rules if r["severity"] in sev_set]

        arm      = self.to_arm_template(rules)
        json_path = OUTPUT_DIR / "sentinel_export.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(arm, f, indent=2)

        md_path = self._generate_markdown(rules)
        return arm, json_path, md_path

    # ------------------------------------------------------------------
    # Markdown summary
    # ------------------------------------------------------------------

    def _generate_markdown(self, rules: list[dict]) -> Path:
        lines = [
            "# DUEL — Sentinel Analytics Rules Export",
            "",
            f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  ",
            f"**Total rules exported:** {len(rules)}  ",
            "",
            "Deploy with:  ",
            "```bash",
            "az deployment group create \\",
            "  --resource-group <rg> \\",
            "  --template-file sentinel_export.json \\",
            "  --parameters workspaceName=<workspace>",
            "```",
            "",
            "## Rules by Severity",
            "",
        ]

        for severity in ("High", "Medium", "Low"):
            bucket = [r for r in rules if r["severity"] == severity]
            if not bucket:
                continue
            lines += [f"### {severity} Severity ({len(bucket)} rules)", ""]
            for rule in bucket:
                eva_pct = f"{rule['evasion_rate']:.0%}"
                det_pct = f"{rule['detection_rate']:.0%}"
                lines += [
                    f"#### {rule['display_name']}",
                    "",
                    f"| Field | Value |",
                    f"|-------|-------|",
                    f"| Technique | `{rule['technique_id']}` — {rule['technique_name']} |",
                    f"| Tactic | {rule['tactic']} |",
                    f"| Round | {rule['round']} |",
                    f"| Detection rate | {det_pct} |",
                    f"| Evasion rate | {eva_pct} |",
                    f"| Severity rationale | Evasion {eva_pct} → {severity} |",
                    f"",
                    f"```kql",
                    rule["kql"].strip(),
                    f"```",
                    f"",
                ]

        lines += ["---", "*Generated by DUEL — Dual Unsupervised Evasion Loop*"]

        md_path = OUTPUT_DIR / "sentinel_export.md"
        with open(md_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return md_path
